spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: a1s2d3

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# App Properties
nurd:
  app:
    jwtSecret: nurdSecretKey
    jwtExpirationMs: 86400000