# Use root/example as user/password credentials
version: '3.1'

services:

  todo-mongodb:
    image: mongo
    container_name: todo-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=todo
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin