# Use root/example as user/password credentials
version: '3.1'

services:

  group-mongodb:
    image: mongo
    container_name: group-mongodb
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=group
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin