# Use root/example as user/password credentials
version: '3.1'

services:

  auth-postgres:
    image: postgres
    container_name: auth-postgres
    ports:
      - 5432:5432
    restart: always

    environment:
      POSTGRES_PASSWORD: a1s2d3

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

